### ISSUE TITLE
Consultant birthdate datepicker outputs wrong format, no field validation applied.

### ISSUE THREAD

**Issue by larsvanherk** [tothepoint-itco/coordinatorentool#51]
Example response for erroneous date "05/02/2016":

```
{
"timestamp":"2016-07-10T09:43:30.372+0000",
"status":400,
"error":"Bad Request",
"exception":"org.springframework.http.converter.HttpMessageNotReadableException",
"message":"Could not read document: Text '05/02/2016' could not be parsed at index 0 (through reference chain: company.tothepoint.model.bediende.Bediende[\"geboorteDatum\"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Text '05/02/2016' could not be parsed at index 0 (through reference chain: company.tothepoint.model.bediende.Bediende[\"geboorteDatum\"])",
"path":"/bediendes"
}
```

**Comment by Kajvdh** [comment]
The output format of the datepick is OK, it should use the dd/MM/yyyy format. This problem would be at the contract-service. But this should have been fixed already, can you verify that you are checked out at the latest version on the master branch of the contract service?

This should be fixed with by annotation: https://github.com/tothepoint-itco/coordinatoren-contract-service/blob/master/src/main/java/company/tothepoint/model/bediende/Bediende.java#L24

**Comment by larsvanherk** [comment]
Format for datepicker has been reverted to the original, most recent local build was done on old code. Looking in to display of field errors.
